import os 
base = r"C:/Users/luizi/agente_convert_moeda_fintech" 
def write_file(rel_path, content): 
    path = os.path.join(base, rel_path) 
    os.makedirs(os.path.dirname(path), exist_ok=True) 
    with open(path, "w", encoding="utf-8") as f: 
        f.write(content) 
    print(f"Written: {rel_path}") 
if __name__ == "__main__": 
    write_file("README.md", "# CambioBot\\n\\nAgente inteligente de otimizacao cambial para viagens via WhatsApp.") 
    write_file(".opencode/plans/PROJECT_MASTER_PLAN.md", "# CambioBot - Plano Mestre\\n\\n> **Produto**: Micro-SaaS B2C (Hotmart) -> B2B White-label\\n> **Stack**: n8n + Evolution API + PostgreSQL + Redis + Python\\n> **Target**: 19M+ brasileiros com perfil viajante\\n\\n## Estrutura\\n```\\nagente_convert_moeda_fintech/\\nÃÄÄ README.md\\nÃÄÄ docs/\\n³   ÃÄÄ microfish/\\n³   ÃÄÄ survey/\\n³   ÃÄÄ architecture/\\n³   ÃÄÄ monetization/\\n³   ÀÄÄ validation/\\nÃÄÄ n8n/workflows/\\nÃÄÄ sql/migrations/\\nÃÄÄ scripts/simulation/\\nÃÄÄ prompts/system/\\nÀÄÄ tests/\\n```\\n\\n## Visao Geral\\n### Problema\\n- US$ 21,7 bi gastos exterior (2025, BC)\\n- 37% citam cambio como barreira (Globo 2025)\\n- Perda media 3-7% = R$ 300-1.500/viagem\\n\\n### Solucao\\nAgente WhatsApp: Coleta -> Planeja (DCA + Mix) -> Monitora -> Executa -> Monetiza\\n\\n### Diferenciais\\n| Feature | Concorrentes | CambioBot |\\n|---------|--------------|-----------|\\n| DCA Automatico | Nao | Sim |\\n| Alertas Trailing | Nao | Sim |\\n| Mix por Pais | Nao | Sim |\\n| Preco Medio Tempo Real | Nao | Sim |\\n| Contexto Macro | Nao | Sim |\\n| WhatsApp Nativo | Nao | Sim |\\n| White-label Bancos | Nao | Sim Fase 3 |\\n\\n## Roadmap\\n- Fase 0: Fundacao (Semanas 1-2) - [x] MicroFish, [x] Questionario, [x] Arquitetura\\n- Fase 1: MVP WhatsApp (Semanas 3-6)\\n- Fase 2: Monetizacao (Semanas 7-12)\\n- Fase 3: B2B White-label (Mes 6+)\\n\\n## Monetizacao\\n| Canal | Mes 6 | Mes 12 |\\n|-------|-------|--------|\\n| Afiliados | R$ 15k | R$ 80k |\\n| Premium R$ 29,90 | R$ 30k | R$ 180k |\\n| Curso Hotmart | R$ 50k | R$ 200k |\\n| B2B | - | R$ 120k |\\n| TOTAL | ~R$ 95k | ~R$ 580k |\\n\\n**Owner**: Luiz | **Target**: 8 semanas") 
    write_file("sql/migrations/001_initial_schema.sql", "-- CambioBot Schema\\nCREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";\\nCREATE TABLE users (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), phone_number VARCHAR(20) UNIQUE);\\nCREATE INDEX idx_users_phone ON users(phone_number);\\nCREATE TABLE trips (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES users(id), destination_country VARCHAR(100), target_currency VARCHAR(3), travel_date DATE, total_budget NUMERIC(12,2));\\nCREATE INDEX idx_trips_user_status ON trips(user_id, status);\\nCREATE TABLE dca_purchases (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), trip_id UUID REFERENCES trips(id), amount_bought NUMERIC(12,2), rate_applied NUMERIC(10,4));\\nCREATE INDEX idx_purchases_trip ON dca_purchases(trip_id);\\nCREATE TABLE exchange_alerts (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES users(id), target_currency VARCHAR(3), alert_type VARCHAR(20), target_rate NUMERIC(10,4), trailing_pct NUMERIC(5,2));\\nCREATE INDEX idx_alerts_active ON exchange_alerts(target_currency, is_active) WHERE is_active = TRUE;\\nCREATE TABLE notification_logs (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES users(id), message_type VARCHAR(30), evolution_message_id VARCHAR(100));\\nCREATE TABLE affiliate_links (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), partner_name VARCHAR(50), tracking_url TEXT, commission_bps INT, priority INT);") 
    write_file("sql/seeds/001_reference_data.sql", "-- Seeds\\nINSERT INTO affiliate_links (partner_name, product_type, target_countries, target_currencies, tracking_url, commission_bps, commission_fixed_brl, priority, requirements) VALUES ('NOMAD', 'CONTA', ARRAY['USA'], ARRAY['USD'], 'https://nomad.app.link/cambiobot?utm_source=cambiobot', 0, 30.00, 10, '{\"min_budget_usd\": 100}');\\nINSERT INTO affiliate_links (partner_name, product_type, target_countries, target_currencies, tracking_url, commission_bps, commission_fixed_brl, priority, requirements) VALUES ('WISE', 'CONTA', ARRAY['USA','EUR','GBR','JPN'], ARRAY['USD','EUR','GBP','JPY'], 'https://wise.com/invite/cambiobot', 50, 0, 10, '{\"min_transfer_usd\": 100}');\\nINSERT INTO affiliate_links (partner_name, product_type, target_countries, target_currencies, tracking_url, commission_bps, commission_fixed_brl, priority, requirements) VALUES ('AVENUE', 'CONTA', ARRAY['USA'], ARRAY['USD'], 'https://avenue.us/cambiobot', 0, 40.00, 10, '{\"min_budget_usd\": 500}');\\nINSERT INTO affiliate_links (partner_name, product_type, target_countries, target_currencies, tracking_url, commission_bps, commission_fixed_brl, priority, requirements) VALUES ('WESTERN_UNION', 'REMESSA', ARRAY['ARG'], ARRAY['ARS','USD'], 'https://westernunion.com.br/cambiobot', 0, 35.00, 10, '{\"destination\": \"ARG\"}');") 
